//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitaWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors
    {
        public int DocId { get; set; }
        public string Name { get; set; }
        public string SurName { get; set; }
        public string Tckn { get; set; }
        public string Gender { get; set; }
        public string DayOfBirth { get; set; }
        public int DepID { get; set; }
    }
}
